server:
  port: 8081

spring:
  application:
    name: anime-review-site
  datasource:
    url: jdbc:postgresql://localhost:5432/anime_review_db
    username: postgres
    password: temp-password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

